<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class KCMS_IDCard {

	/* Column order expected in the uploaded Excel/CSV template - keep this
	   in sync with the template generated by admin_post_kcms_download_template(). */
	const COLUMNS = array( 'roll_number', 'name', 'father_name', 'dob', 'address', 'mobile', 'email', 'class', 'branch', 'session', 'blood_group', 'gender', 'photo_filename' );

	public static function init() {
		add_shortcode( 'kcms_my_id_card', array( __CLASS__, 'shortcode_my_id_card' ) );
		add_action( 'admin_post_kcms_idcard_upload', array( __CLASS__, 'handle_upload' ) );
		add_action( 'admin_post_kcms_download_template', array( __CLASS__, 'download_template' ) );
		add_action( 'admin_post_kcms_idcard_generate', array( __CLASS__, 'handle_generate' ) );
		add_action( 'admin_post_kcms_idcard_photo', array( __CLASS__, 'handle_photo_upload' ) );
		add_action( 'admin_post_kcms_idcard_delete', array( __CLASS__, 'handle_delete' ) );
	}

	public static function download_template() {
		if ( ! current_user_can( 'kcms_manage_idcards' ) ) wp_die( 'Not allowed.' );
		check_admin_referer( 'kcms_download_template' );
		nocache_headers();
		header( 'Content-Type: text/csv; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename="id-card-upload-template.csv"' );
		echo implode( ',', self::COLUMNS ) . "\r\n";
		echo "101,Demo Student,Demo Father,2005-06-15,\"Katapali, Bijepur, Bargarh\",9876543210,demo@example.com,+3 1st Year,Science,2025-26,B+,Male,101.jpg\r\n";
		exit;
	}

	/* Accepts .xlsx (via KCMS_Xlsx_Reader) or .csv (via fgetcsv) - both map
	   to the same COLUMNS order. Photos are matched afterwards by
	   photo_filename against files uploaded in the same batch (a .zip of
	   images), matched to the roll number. */
	public static function handle_upload() {
		if ( ! current_user_can( 'kcms_manage_idcards' ) ) wp_die( 'Not allowed.' );
		check_admin_referer( 'kcms_idcard_upload' );

		if ( empty( $_FILES['data_file']['tmp_name'] ) ) {
			self::redirect_with_msg( 'No file uploaded.' );
		}
		$tmp = $_FILES['data_file']['tmp_name'];
		$name = sanitize_file_name( $_FILES['data_file']['name'] );
		$ext = strtolower( pathinfo( $name, PATHINFO_EXTENSION ) );

		if ( 'xlsx' === $ext ) {
			$rows = KCMS_Xlsx_Reader::read( $tmp );
			if ( is_wp_error( $rows ) ) self::redirect_with_msg( $rows->get_error_message() );
		} elseif ( 'csv' === $ext ) {
			$rows = array();
			if ( ( $handle = fopen( $tmp, 'r' ) ) !== false ) {
				while ( ( $line = fgetcsv( $handle, 0, ',', '"', '\\' ) ) !== false ) { $rows[] = $line; }
				fclose( $handle );
			}
		} else {
			self::redirect_with_msg( 'Please upload a .xlsx or .csv file.' );
		}

		if ( empty( $rows ) ) self::redirect_with_msg( 'The file appears to be empty.' );
		array_shift( $rows ); // header row

		global $wpdb;
		$table = KCMS_DB::t( 'id_cards' );
		$stu_table = KCMS_DB::t( 'students' );
		$success = 0; $errors = array();
		$seen_rolls = array();

		foreach ( $rows as $i => $row ) {
			$line_no = $i + 2;
			$row = array_pad( $row, count( self::COLUMNS ), '' );
			$data = array_combine( self::COLUMNS, array_slice( $row, 0, count( self::COLUMNS ) ) );
			$roll = trim( $data['roll_number'] );
			if ( '' === $roll ) { $errors[] = "Line {$line_no}: missing roll number - skipped."; continue; }
			if ( isset( $seen_rolls[ $roll ] ) ) { $errors[] = "Line {$line_no}: duplicate roll number '{$roll}' in this file - skipped."; continue; }
			if ( '' === trim( $data['name'] ) ) { $errors[] = "Line {$line_no}: missing student name - skipped."; continue; }
			$seen_rolls[ $roll ] = true;

			$existing_id = $wpdb->get_var( $wpdb->prepare( "SELECT id_card_id FROM {$table} WHERE roll_number=%s", $roll ) );
			$now = current_time( 'mysql' );
			$record = array(
				'roll_number' => $roll,
				'name'        => sanitize_text_field( $data['name'] ),
				'father_name' => sanitize_text_field( $data['father_name'] ),
				'dob'         => self::parse_date( $data['dob'] ),
				'address'     => sanitize_textarea_field( $data['address'] ),
				'mobile_enc'  => $data['mobile'] ? KCMS_Crypto::encrypt( preg_replace( '/\D/', '', $data['mobile'] ) ) : '',
				'phone_hash'  => $data['mobile'] ? KCMS_Crypto::hash_phone( preg_replace( '/\D/', '', $data['mobile'] ) ) : '',
				'email'       => sanitize_email( $data['email'] ),
				'class'       => sanitize_text_field( $data['class'] ),
				'branch'      => sanitize_text_field( $data['branch'] ),
				'session'     => sanitize_text_field( $data['session'] ),
				'blood_group' => sanitize_text_field( $data['blood_group'] ),
				'gender'      => sanitize_text_field( $data['gender'] ),
				'updated_at'  => $now,
			);

			if ( $existing_id ) {
				$wpdb->update( $table, $record, array( 'id_card_id' => $existing_id ) );
				$id_card_id = $existing_id;
			} else {
				$record['created_at'] = $now;
				$record['status'] = 'active';
				$record['member_id'] = '';
				$wpdb->insert( $table, $record );
				$id_card_id = $wpdb->insert_id;
				$wpdb->update( $table, array( 'member_id' => KCMS_Numbering::member_id( $id_card_id ) ), array( 'id_card_id' => $id_card_id ) );
			}

			// keep a matching master row in kcms_students for the certificate portal
			$student_row = $wpdb->get_row( $wpdb->prepare( "SELECT student_id FROM {$stu_table} WHERE college_roll_no=%s", $roll ) );
			$stu_record = array(
				'name'               => $record['name'],
				'father_name'        => $record['father_name'],
				'university_roll_no' => '',
				'email'              => $record['email'],
				'phone_enc'          => $record['mobile_enc'],
				'updated_at'         => $now,
			);
			if ( $student_row ) {
				$wpdb->update( $stu_table, $stu_record, array( 'student_id' => $student_row->student_id ) );
			} else {
				$stu_record['college_roll_no'] = $roll;
				$stu_record['status'] = 'active';
				$stu_record['created_at'] = $now;
				$wpdb->insert( $stu_table, $stu_record );
			}

			$success++;
		}

		$wpdb->insert( KCMS_DB::t( 'excel_uploads' ), array(
			'upload_date'       => current_time( 'mysql' ),
			'file_name'         => $name,
			'total_records'     => count( $rows ),
			'success_count'     => $success,
			'error_count'       => count( $errors ),
			'error_details'     => wp_json_encode( $errors ),
			'uploaded_by'       => get_current_user_id(),
			'processing_status' => 'completed',
		) );
		KCMS_DB::log( 'idcard_bulk_upload', 'excel_upload', $wpdb->insert_id, array( 'success' => $success, 'errors' => count( $errors ) ) );

		self::redirect_with_msg( "Import complete: {$success} imported/updated, " . count( $errors ) . ' error(s). See the Uploads Log for details.' );
	}

	private static function parse_date( $val ) {
		$val = trim( (string) $val );
		if ( '' === $val ) return null;
		$ts = strtotime( $val );
		return $ts ? gmdate( 'Y-m-d', $ts ) : null;
	}

	private static function redirect_with_msg( $msg ) {
		wp_safe_redirect( add_query_arg( array( 'page' => 'kcms-idcards', 'kcms_msg' => rawurlencode( $msg ) ), admin_url( 'admin.php' ) ) );
		exit;
	}

	public static function handle_photo_upload() {
		if ( ! current_user_can( 'kcms_manage_idcards' ) ) wp_die( 'Not allowed.' );
		check_admin_referer( 'kcms_idcard_photo' );
		$id = absint( $_POST['id'] ?? 0 );
		if ( ! $id || empty( $_FILES['photo']['name'] ) ) self::redirect_with_msg( 'No photo provided.' );
		$uploaded = KCMS_Leave::handle_upload( 'photo' );
		if ( is_wp_error( $uploaded ) ) self::redirect_with_msg( $uploaded->get_error_message() );
		global $wpdb;
		$wpdb->update( KCMS_DB::t( 'id_cards' ), array( 'photo_path' => $uploaded, 'photo_upload_date' => current_time( 'mysql' ) ), array( 'id_card_id' => $id ) );
		self::redirect_with_msg( 'Photo updated.' );
	}

	public static function handle_generate() {
		if ( ! current_user_can( 'kcms_manage_idcards' ) ) wp_die( 'Not allowed.' );
		check_admin_referer( 'kcms_idcard_generate' );
		global $wpdb;
		$id = absint( $_POST['id'] ?? 0 );
		$which = sanitize_text_field( wp_unslash( $_POST['which'] ?? '' ) );
		$field = 'library' === $which ? 'library_card_generated' : 'id_card_generated';
		$wpdb->update( KCMS_DB::t( 'id_cards' ), array( $field => 1, 'issue_date' => current_time( 'mysql', false ), 'updated_at' => current_time( 'mysql' ) ), array( 'id_card_id' => $id ) );
		KCMS_DB::log( 'idcard_generated', 'id_card', $id, $which );
		self::redirect_with_msg( 'Card marked as generated.' );
	}

	public static function handle_delete() {
		if ( ! current_user_can( 'kcms_manage_idcards' ) ) wp_die( 'Not allowed.' );
		check_admin_referer( 'kcms_idcard_delete' );
		global $wpdb;
		$id = absint( $_POST['id'] ?? 0 );
		$wpdb->delete( KCMS_DB::t( 'id_cards' ), array( 'id_card_id' => $id ) );
		KCMS_DB::log( 'idcard_deleted', 'id_card', $id );
		self::redirect_with_msg( 'Record deleted.' );
	}

	public static function shortcode_my_id_card() {
		if ( ! is_user_logged_in() ) {
			return '<div class="kcms-box kcms-notice">Please log in to view your ID card. <a href="' . esc_url( add_query_arg( 'type', 'student', KCMS_Login::login_page_url() ) ) . '">Log in</a></div>';
		}
		global $wpdb;
		$user = wp_get_current_user();
		$table = KCMS_DB::t( 'id_cards' );
		$card = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE email=%s", $user->user_email ) );
		if ( ! $card ) {
			return '<div class="kcms-box kcms-notice">No ID card record found for your account yet. Please contact the college office.</div>';
		}
		ob_start();
		include KCMS_DIR . 'templates/idcard-portal.php';
		return ob_get_clean();
	}

	private static function get_card( $id ) {
		global $wpdb;
		$table = KCMS_DB::t( 'id_cards' );
		return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE id_card_id=%d", $id ) );
	}

	private static function can_view( $card ) {
		if ( ! $card ) return false;
		if ( current_user_can( 'kcms_manage_idcards' ) ) return true;
		if ( is_user_logged_in() ) {
			$user = wp_get_current_user();
			return $card->email && strtolower( $card->email ) === strtolower( $user->user_email );
		}
		return false;
	}

	public static function render_id_card_print( $id ) {
		$card = self::get_card( $id );
		if ( ! self::can_view( $card ) ) { status_header( 403 ); echo 'Not allowed.'; return; }
		include KCMS_DIR . 'templates/idcard-print.php';
	}

	public static function render_library_card_print( $id ) {
		$card = self::get_card( $id );
		if ( ! self::can_view( $card ) ) { status_header( 403 ); echo 'Not allowed.'; return; }
		include KCMS_DIR . 'templates/librarycard-print.php';
	}
}
KCMS_IDCard::init();
